#!/usr/bin/env node
/**
 * Generates the blog: blog/index.html + blog/<slug>/index.html
 *
 * Source of truth:
 *   blog/posts/*.md             — markdown posts with YAML-ish frontmatter
 *   templates/blog-index.html, templates/blog-post.html
 *
 * Frontmatter keys: title, description, date (YYYY-MM-DD), slug.
 * Minimal self-contained markdown → HTML (no deps): headings, paragraphs,
 * lists, bold, inline code, links, hr. JSON-LD: BlogPosting + Breadcrumb (post),
 * Blog + Breadcrumb (index).
 *
 * Usage:
 *   node scripts/build-blog.js            # build all
 *   node scripts/build-blog.js --dry-run
 */

const fs   = require('fs');
const path = require('path');
const { loadTemplate } = require('./lib/render');
const { loadDict, transformToEn, hreflangBlock } = require('./lib/en-transform');
const { iconSvg, coverGradient, pickIcon } = require('./lib/blog-cover');

const BASE_URL  = 'https://trace-logos.ru';
const ROOT      = path.resolve(__dirname, '..');
const POSTS_DIR = path.join(ROOT, 'blog', 'posts');
const T_INDEX   = loadTemplate(path.join(ROOT, 'templates', 'blog-index.html'));
const T_POST    = loadTemplate(path.join(ROOT, 'templates', 'blog-post.html'));
const DRY_RUN   = process.argv.includes('--dry-run');
const EN        = loadDict().en;

const MONTHS    = ['января','февраля','марта','апреля','мая','июня','июля','августа','сентября','октября','ноября','декабря'];
const MONTHS_EN = ['January','February','March','April','May','June','July','August','September','October','November','December'];

function esc(str) {
  return String(str || '')
    .replace(/&/g, '&amp;').replace(/</g, '&lt;')
    .replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

// Per-post OG image — generated by build-blog-og-images.js (opt-in slow tier, same
// convention as build-og-images.js for logo pages: the URL is emitted unconditionally,
// test-data.js --post warns if the file is actually missing on disk.
function ogImageFor(slug) {
  return `${BASE_URL}/assets/og/blog-${slug}.png`;
}

// Frontmatter: --- ... --- at top of file
// Supports optional EN body section after a `---EN---` line
function parseFrontmatter(raw) {
  const m = raw.match(/^---\n([\s\S]*?)\n---\n?([\s\S]*)$/);
  if (!m) return { meta: {}, body: raw, body_en: null };
  const meta = {};
  for (const line of m[1].split('\n')) {
    const i = line.indexOf(':');
    if (i === -1) continue;
    meta[line.slice(0, i).trim()] = line.slice(i + 1).trim();
  }
  const parts = m[2].split(/\n---EN---\n/);
  return { meta, body: parts[0], body_en: parts[1] || null };
}

// Inline: bold, inline code, links. Input is already-escaped text.
function inline(text) {
  return text
    .replace(/`([^`]+)`/g, (_, c) => `<code>${c}</code>`)
    .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
    .replace(/\*([^*]+)\*/g, '<em>$1</em>')   // italic — after bold so ** isn't eaten
    .replace(/\[([^\]]+)\]\(([^)]+)\)/g, (_, t, href) => `<a href="${href}" target="_blank" rel="noopener">${t}</a>`);
}

// Non-breaking spaces for Russian typography — keeps short prepositions/conjunctions,
// number+unit pairs, and dashes from being orphaned at a line break. Runs on raw
// markdown text before esc()/inline(), with code spans and links protected so nbsp
// never leaks into `code`, URLs, or link text.
const NBSP = ' ';
const SHORT_WORDS = 'в|к|с|у|о|и|а|но|же|ли|бы|из|за|до|по|от|на|для|при|не|что|как|или|там|тут|уже|чем|это|над|под|со|во|ко|та|то|же|ж|б|же';
const RE_SHORT_WORD = new RegExp(`(^|[\\s(«"'])(${SHORT_WORDS})[ ](?=\\S)`, 'giu');
const RE_NUMBER_UNIT = /(\d+)[ ](мб|кб|гб|тб|px|см|мм|кг|г|лет|дня|дней|день|года|год|руб|₽|%|мин|ч|км)\b/giu;
const RE_DASH = /(\S)[ ](—|–)[ ]/g;

function typo(text) {
  const placeholders = [];
  const protect = m => { placeholders.push(m); return `\u0000${placeholders.length - 1}\u0000`; };
  let t = text.replace(/`[^`]+`|\[[^\]]+\]\([^)]+\)/g, protect);
  t = t.replace(RE_SHORT_WORD, (_, pre, w) => `${pre}${w}${NBSP}`);
  t = t.replace(RE_NUMBER_UNIT, (_, n, u) => `${n}${NBSP}${u}`);
  t = t.replace(RE_DASH, (_, before, dash) => `${before}${NBSP}${dash} `);
  return t.replace(/\u0000(\d+)\u0000/g, (_, i) => placeholders[Number(i)]);
}

function slugifyHeading(text) {
  return String(text).toLowerCase().trim()
    .replace(/[^\wа-яё]+/gi, '-').replace(/^-+|-+$/g, '');
}

// Callout blocks (`:::type [Заголовок]` … `:::`) — the main readability tool.
// Each type = accent colour + icon + a default localized label (overridable by
// a title on the fence line). SVG icons match the site's stroke-icon look.
const CALLOUT_ICONS = {
  note:    '<circle cx="12" cy="12" r="9"/><path d="M12 8h.01M11 12h1v4h1"/>',
  tip:     '<path d="M9 18h6M10 21h4M12 3a6 6 0 0 0-4 10.5c.7.7 1 1.2 1 2.5h6c0-1.3.3-1.8 1-2.5A6 6 0 0 0 12 3Z"/>',
  warning: '<path d="M12 9v4m0 4h.01M10.3 3.9 1.8 18a2 2 0 0 0 1.7 3h17a2 2 0 0 0 1.7-3L13.7 3.9a2 2 0 0 0-3.4 0Z"/>',
  success: '<circle cx="12" cy="12" r="9"/><path d="m8.5 12 2.5 2.5 4.5-5"/>',
  danger:  '<circle cx="12" cy="12" r="9"/><path d="m15 9-6 6M9 9l6 6"/>',
};
const CALLOUT_LABELS = {
  note:    { ru: 'Заметка', en: 'Note' },
  tip:     { ru: 'Совет',   en: 'Tip' },
  warning: { ru: 'Важно',   en: 'Important' },
  success: { ru: 'Можно',   en: 'Allowed' },
  danger:  { ru: 'Нельзя',  en: 'Not allowed' },
};

function calloutHead(type, title, lang) {
  const icon = CALLOUT_ICONS[type] || CALLOUT_ICONS.note;
  const label = title || (CALLOUT_LABELS[type] || CALLOUT_LABELS.note)[lang] || '';
  const svg = `<svg class="callout-icon" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true">${icon}</svg>`;
  return label ? `<div class="callout-head">${svg}<span>${inline(esc(label))}</span></div>` : svg;
}

// One pass over a block of lines → HTML. Recursive: callouts re-enter this to
// render their own body. `headings` collects H2s for the auto table of contents.
function renderBlocks(lines, lang, headings) {
  const out = [];
  let i = 0, listType = null;
  const closeList = () => { if (listType) { out.push(`</${listType}>`); listType = null; } };

  while (i < lines.length) {
    const t = lines[i].trim();

    if (!t) { closeList(); i++; continue; }

    if (t === '---') { closeList(); out.push('<hr>'); i++; continue; }

    // Fenced code block: ```lang ... ``` — raw content, no inline markdown processing.
    const codeFence = t.match(/^```(\w*)\s*$/);
    if (codeFence) {
      closeList();
      const codeLang = codeFence[1] || '';
      const code = [];
      i++;
      while (i < lines.length && lines[i].trim() !== '```') { code.push(lines[i]); i++; }
      i++; // skip closing fence
      const label = codeLang ? esc(codeLang) : (lang === 'en' ? 'code' : 'код');
      out.push(`<div class="blog-code">
        <div class="blog-code-head">
          <span class="blog-code-lang">${label}</span>
          <button type="button" class="blog-code-copy" data-copy-label="${lang === 'en' ? 'Copy' : 'Копировать'}" data-copied-label="${lang === 'en' ? 'Copied' : 'Скопировано'}">
            <svg width="13" height="13" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="9" y="9" width="13" height="13" rx="2"/><path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1"/></svg>
            <span>${lang === 'en' ? 'Copy' : 'Копировать'}</span>
          </button>
        </div>
        <pre><code class="language-${esc(codeLang)}">${esc(code.join('\n'))}</code></pre>
      </div>`);
      continue;
    }

    // Callout fence: `:::type` or `:::type Custom title`
    const co = t.match(/^:::(\w+)(?:\s+(.*))?$/);
    if (co) {
      closeList();
      const type = co[1], title = (co[2] || '').trim();
      const inner = [];
      i++;
      while (i < lines.length && lines[i].trim() !== ':::') { inner.push(lines[i]); i++; }
      i++; // skip closing :::
      out.push(`<div class="callout callout-${esc(type)}">${calloutHead(type, title, lang)}<div class="callout-body">${renderBlocks(inner, lang, [])}</div></div>`);
      continue;
    }

    // Blockquote: consecutive `> ` lines
    if (/^>\s?/.test(t)) {
      closeList();
      const quote = [];
      while (i < lines.length && /^>\s?/.test(lines[i].trim())) { quote.push(lines[i].trim().replace(/^>\s?/, '')); i++; }
      out.push(`<blockquote>${renderBlocks(quote, lang, [])}</blockquote>`);
      continue;
    }

    // Pipe table: header row + `|---|---|` separator
    if (t.startsWith('|') && i + 1 < lines.length && /^\|[\s:|-]+\|?\s*$/.test(lines[i + 1].trim())) {
      closeList();
      const cells = row => row.trim().replace(/^\||\|$/g, '').split('|').map(c => c.trim());
      const head = cells(lines[i]); i += 2;
      const body = [];
      while (i < lines.length && lines[i].trim().startsWith('|')) { body.push(cells(lines[i])); i++; }
      const thead = `<thead><tr>${head.map(c => `<th>${inline(esc(typo(c)))}</th>`).join('')}</tr></thead>`;
      const tbody = `<tbody>${body.map(r => `<tr>${r.map(c => `<td>${inline(esc(typo(c)))}</td>`).join('')}</tr>`).join('')}</tbody>`;
      out.push(`<div class="blog-table-wrap"><table class="blog-table">${thead}${tbody}</table></div>`);
      continue;
    }

    // Headings (## / ###). H2s get an anchor id and feed the TOC.
    const h = t.match(/^(#{2,3})\s+(.*)$/);
    if (h) {
      closeList();
      const lvl = h[1].length;
      if (lvl === 2) {
        const id = slugifyHeading(h[2]);
        headings.push({ id, text: esc(stripMd(h[2])) });
        // «Шаг N. Название» / "Step N. Title" → badge + title on its own line
        const step = h[2].match(/^(Шаг|Step)\s+(\d+)\.\s*(.+)$/);
        if (step) {
          const titleHtml = inline(esc(typo(step[3]))).replace(/\(([^)]+)\)/g, '<span class="step-title-dim">($1)</span>');
          out.push(`<h2 id="${id}" class="step-heading"><span class="step-badge">${step[1]}&nbsp;${step[2]}</span><span class="step-title">${titleHtml}</span></h2>`);
        } else {
          out.push(`<h2 id="${id}">${inline(esc(typo(h[2])))}</h2>`);
        }
      } else {
        out.push(`<h3>${inline(esc(typo(h[2])))}</h3>`);
      }
      i++; continue;
    }

    const ul = t.match(/^[-*]\s+(.*)$/);
    if (ul) {
      if (listType !== 'ul') { closeList(); listType = 'ul'; out.push('<ul>'); }
      out.push(`<li>${inline(esc(typo(ul[1])))}</li>`); i++; continue;
    }
    const ol = t.match(/^\d+\.\s+(.*)$/);
    if (ol) {
      if (listType !== 'ol') { closeList(); listType = 'ol'; out.push('<ol>'); }
      out.push(`<li>${inline(esc(typo(ol[1])))}</li>`); i++; continue;
    }

    // Paragraph: gather until blank line or the next block marker
    closeList();
    const para = [];
    while (i < lines.length && lines[i].trim() &&
           !/^(#{2,3}\s|[-*]\s|\d+\.\s|>\s?|:::|```|\||---$)/.test(lines[i].trim())) {
      para.push(lines[i].trim()); i++;
    }
    out.push(`<p>${inline(esc(typo(para.join(' '))))}</p>`);
  }
  closeList();
  return out.join('\n      ');
}

// Block-level markdown → HTML. Returns headings (H2s) alongside the body so
// the caller can build the auto-generated section-nav sidebar.
function mdToHtml(md, lang = 'ru') {
  const headings = [];
  const body = renderBlocks(md.replace(/\r\n/g, '\n').split('\n'), lang, headings);
  return { body, headings };
}

// Sidebar: reading-progress bar + auto section nav (≥2 H2s, active item
// highlighted on scroll by js/blog-toc.js) + a catalog link pinned at the
// bottom. Generated for every post — this is what makes the sidebar "self-generating".
function buildSidebar(headings, lang) {
  const navLabel = lang === 'en' ? 'On this page' : 'В этой статье';
  const progressLabel = lang === 'en' ? 'Reading progress' : 'Прогресс чтения';
  const progress = `<div class="blog-progress-wrap">
      <div class="blog-progress" role="progressbar" aria-label="${progressLabel}" aria-valuemin="0" aria-valuemax="100"><div class="blog-progress-bar"></div></div>
      <span class="blog-progress-pct">0%</span>
    </div>`;
  let nav = '';
  if (headings.length >= 2) {
    const items = headings.map(h => `<li><a href="#${h.id}">${h.text}</a></li>`).join('');
    nav = `<nav class="blog-sidebar-nav" aria-label="${navLabel}"><span class="blog-sidebar-label">${navLabel}</span><ol>${items}</ol></nav>`;
  }
  return nav + '\n      ' + progress;
}

// Approximate reading time (~180 wpm for RU prose).
function readTime(md, lang = 'ru') {
  const words = stripMd(md).replace(/[#>*`|:-]/g, ' ').split(/\s+/).filter(Boolean).length;
  const min = Math.max(1, Math.round(words / 180));
  return lang === 'en' ? `${min} min read` : `${min} мин чтения`;
}

function humanDate(iso, lang = 'ru') {
  const [y, m, d] = iso.split('-').map(Number);
  if (lang === 'en') return `${MONTHS_EN[m - 1]} ${d}, ${y}`;
  return `${d} ${MONTHS[m - 1]} ${y}`;
}

function shortDate(iso) {
  const [y, m, d] = iso.split('-');
  return `${d}.${m}.${y}`;
}

// Related posts widget (bottom of article) — ranked by shared tags, ties
// broken by recency. Falls back to the most recent other posts when a post
// has too few tag matches to fill the widget.
const RELATED_COUNT = 6;
function pickRelated(post, allPosts, n = RELATED_COUNT) {
  return allPosts
    .filter(p => p.slug !== post.slug)
    .map(p => ({ p, shared: p.tags.filter(t => post.tags.includes(t)).length }))
    .sort((a, b) => b.shared - a.shared || b.p.date.localeCompare(a.p.date))
    .slice(0, n)
    .map(s => s.p);
}

function relatedCard(p, i, lang) {
  const coverStyle = p.cover
    ? `background-image: url('${esc(p.cover)}'); background-size: cover; background-position: center;`
    : coverGradient(i);
  const coverInner = p.cover ? '' : iconSvg(pickIcon(p.slug), 40, 'blog-card-icon');
  const title = lang === 'en' ? p.title_en : p.title;
  return `<a class="blog-card" href="../${p.slug}/">
        <div class="blog-card-cover" style="${coverStyle}" aria-hidden="true">${coverInner}</div>
        <div class="blog-card-body">
          <div class="blog-card-date">${shortDate(p.date)}</div>
          <div class="blog-card-title">${esc(title)}</div>
        </div>
      </a>`;
}

function relatedCardsHtml(list, lang) {
  return list.map((p, i) => relatedCard(p, i, lang)).join('\n      ');
}

// Strip inline markdown markers for plain-text excerpts/descriptions.
function stripMd(text) {
  return text
    .replace(/`([^`]+)`/g, '$1')
    .replace(/\*\*([^*]+)\*\*/g, '$1')
    .replace(/\[([^\]]+)\]\([^)]+\)/g, '$1');
}

function firstParagraph(md) {
  for (const block of md.split(/\n\s*\n/)) {
    const t = block.trim();
    if (t && !/^(#|---|[-*]\s|\d+\.\s)/.test(t)) return stripMd(t.replace(/\s+/g, ' '));
  }
  return '';
}

function main() {
  if (!fs.existsSync(POSTS_DIR)) { console.error('✗ blog/posts/ not found'); process.exit(1); }

  const files = fs.readdirSync(POSTS_DIR).filter(f => f.endsWith('.md'));
  const posts = files.map(f => {
    const raw = fs.readFileSync(path.join(POSTS_DIR, f), 'utf8');
    const { meta, body, body_en } = parseFrontmatter(raw);
    const slug = meta.slug || path.basename(f, '.md');
    const tags = meta.tags ? meta.tags.split(',').map(t => t.trim()).filter(Boolean) : [];
    const tags_en = meta.tags_en ? meta.tags_en.split(',').map(t => t.trim()).filter(Boolean) : tags;
    return {
      slug,
      title: meta.title || slug,
      title_en: meta.title_en || meta.title || slug,
      description: meta.description || firstParagraph(body).slice(0, 160),
      description_en: meta.description_en || meta.description || firstParagraph(body).slice(0, 160),
      date: meta.date || '1970-01-01',
      excerpt: firstParagraph(body).slice(0, 180),
      tags,
      tags_en,
      cover: meta.cover || '',
      body,
      body_en: body_en || null,
    };
  }).sort((a, b) => b.date.localeCompare(a.date));   // newest first

  if (DRY_RUN) {
    posts.forEach(p => console.log(`blog/${p.slug}/index.html  — ${p.title}`));
    console.log(`\nblog/index.html  (${posts.length} posts)`);
    return;
  }

  // ── Post pages ──
  posts.forEach((p, i) => {
    const rel = '../../';
    const coverStyle = p.cover
      ? `background-image: url('${esc(p.cover)}'); background-size: cover; background-position: center;`
      : coverGradient(i);
    const coverIcon = p.cover ? '' : iconSvg(pickIcon(p.slug), 72, 'blog-article-icon');
    const fullUrl = `${BASE_URL}/blog/${p.slug}/`;
    const jsonLd = JSON.stringify({
      "@context": "https://schema.org",
      "@graph": [
        {
          "@type": "BreadcrumbList",
          "itemListElement": [
            { "@type": "ListItem", "position": 1, "name": "Trace Logo's", "item": `${BASE_URL}/` },
            { "@type": "ListItem", "position": 2, "name": "Блог", "item": `${BASE_URL}/blog/` },
            { "@type": "ListItem", "position": 3, "name": p.title, "item": fullUrl },
          ],
        },
        {
          "@type": "BlogPosting",
          "headline": p.title,
          "description": p.description,
          "datePublished": p.date,
          "dateModified": p.date,
          "url": fullUrl,
          "inLanguage": "ru",
          "image": ogImageFor(p.slug),
          "author": { "@type": "Organization", "name": "Trace Logo's" },
          "publisher": { "@type": "Organization", "name": "Trace Logo's" },
          "mainEntityOfPage": fullUrl,
        },
      ],
    }, null, 2);

    const { body: ruBody, headings: ruHeadings } = mdToHtml(p.body, 'ru');
    const related = pickRelated(p, posts);
    const vars = {
      REL: rel,
      HOME_REL: rel,
      DATA_BASE: rel,
      TITLE: `${p.title} · Trace Logo's`,
      META_DESC: esc(p.description),
      CANONICAL_URL: fullUrl,
      HREFLANG_TAGS: hreflangBlock(fullUrl, `${BASE_URL}/en/blog/${p.slug}/`),
      OG_TITLE: esc(p.title),
      OG_IMAGE: ogImageFor(p.slug),
      DATE_ISO: p.date,
      DATE_HUMAN: humanDate(p.date),
      READ_TIME: readTime(p.body, 'ru'),
      JSON_LD: jsonLd,
      H1: esc(p.title),
      COVER_STYLE: coverStyle,
      COVER_ICON: coverIcon,
      BODY: ruBody,
      SIDEBAR: buildSidebar(ruHeadings, 'ru'),
      RELATED_POSTS: relatedCardsHtml(related, 'ru'),
    };
    const html = T_POST.replace(/\{\{(\w+)\}\}/g, (_, k) => {
      if (!(k in vars)) { console.warn(`Unknown placeholder {{${k}}}`); return ''; }
      return vars[k];
    });
    const outPath = path.join(ROOT, 'blog', p.slug, 'index.html');
    fs.mkdirSync(path.dirname(outPath), { recursive: true });
    fs.writeFileSync(outPath, html, 'utf8');

    // EN page — English title/meta/JSON-LD + EN body when available
    const enFullUrl = `${BASE_URL}/en/blog/${p.slug}/`;
    const enJsonLd = JSON.stringify({
      "@context": "https://schema.org",
      "@graph": [
        {
          "@type": "BreadcrumbList",
          "itemListElement": [
            { "@type": "ListItem", "position": 1, "name": "Trace Logo's", "item": `${BASE_URL}/` },
            { "@type": "ListItem", "position": 2, "name": "Blog", "item": `${BASE_URL}/en/blog/` },
            { "@type": "ListItem", "position": 3, "name": p.title_en, "item": enFullUrl },
          ],
        },
        {
          "@type": "BlogPosting",
          "headline": p.title_en,
          "description": p.description_en,
          "datePublished": p.date,
          "dateModified": p.date,
          "url": enFullUrl,
          "inLanguage": "en",
          "image": ogImageFor(p.slug),
          "author": { "@type": "Organization", "name": "Trace Logo's" },
          "publisher": { "@type": "Organization", "name": "Trace Logo's" },
          "mainEntityOfPage": enFullUrl,
        },
      ],
    }, null, 2);
    const { body: enBody, headings: enHeadings } = p.body_en ? mdToHtml(p.body_en, 'en') : mdToHtml(p.body, 'en');
    const enVars = {
      ...vars,
      HOME_REL: '/en/',
      DATA_BASE: '/',
      TITLE: `${p.title_en} · Trace Logo's`,
      META_DESC: esc(p.description_en),
      OG_TITLE: esc(p.title_en),
      H1: esc(p.title_en),
      DATE_HUMAN: humanDate(p.date, 'en'),
      READ_TIME: readTime(p.body_en || p.body, 'en'),
      JSON_LD: enJsonLd,
      BODY: enBody,
      SIDEBAR: buildSidebar(enHeadings, 'en'),
      RELATED_POSTS: relatedCardsHtml(related, 'en'),
    };
    const htmlEn = transformToEn(
      T_POST.replace(/\{\{(\w+)\}\}/g, (_, k) => (k in enVars ? enVars[k] : '')),
      `blog/${p.slug}/index.html`,
      EN
    );
    const enOutPath = path.join(ROOT, 'en', 'blog', p.slug, 'index.html');
    fs.mkdirSync(path.dirname(enOutPath), { recursive: true });
    fs.writeFileSync(enOutPath, htmlEn, 'utf8');
  });

  // ── Index page ──
  const cards = posts.map((p, i) => {
    const coverStyle = p.cover
      ? `background-image: url('${esc(p.cover)}'); background-size: cover; background-position: center;`
      : coverGradient(i);
    const coverInner = p.cover ? '' : iconSvg(pickIcon(p.slug), 40, 'blog-card-icon');
    const tagsHtml = p.tags.length
      ? `<div class="blog-card-tags">${p.tags.map(t => `<span class="blog-card-tag">${esc(t)}</span>`).join('')}</div>`
      : '';
    return `<a class="blog-card" href="${p.slug}/">
        <div class="blog-card-cover" style="${coverStyle}" aria-hidden="true">${coverInner}</div>
        <div class="blog-card-body">
          <div class="blog-card-date">${shortDate(p.date)}</div>
          <div class="blog-card-title">${esc(p.title)}</div>
          ${tagsHtml}
        </div>
      </a>`;
  }).join('\n      ');

  const indexJsonLd = JSON.stringify({
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "BreadcrumbList",
        "itemListElement": [
          { "@type": "ListItem", "position": 1, "name": "Trace Logo's", "item": `${BASE_URL}/` },
          { "@type": "ListItem", "position": 2, "name": "Блог", "item": `${BASE_URL}/blog/` },
        ],
      },
      {
        "@type": "Blog",
        "name": "Блог Trace Logo's",
        "url": `${BASE_URL}/blog/`,
        "inLanguage": "ru",
        "blogPost": posts.map(p => ({
          "@type": "BlogPosting",
          "headline": p.title,
          "url": `${BASE_URL}/blog/${p.slug}/`,
          "datePublished": p.date,
        })),
      },
    ],
  }, null, 2);

  const indexHtml = T_INDEX.replace(/\{\{(\w+)\}\}/g, (_, k) => {
    if (k === 'REL' || k === 'HOME_REL' || k === 'DATA_BASE') return '../';
    if (k === 'JSON_LD') return indexJsonLd;
    if (k === 'POST_CARDS') return cards;
    console.warn(`Unknown placeholder {{${k}}}`); return '';
  });
  fs.writeFileSync(path.join(ROOT, 'blog', 'index.html'), indexHtml, 'utf8');

  // ── EN blog index — same structure, English card titles ──
  const enCards = posts.map((p, i) => {
    const coverStyle = p.cover
      ? `background-image: url('${esc(p.cover)}'); background-size: cover; background-position: center;`
      : coverGradient(i);
    const coverInner = p.cover ? '' : iconSvg(pickIcon(p.slug), 40, 'blog-card-icon');
    const tagsHtml = p.tags_en.length
      ? `<div class="blog-card-tags">${p.tags_en.map(t => `<span class="blog-card-tag">${esc(t)}</span>`).join('')}</div>`
      : '';
    return `<a class="blog-card" href="${p.slug}/">
        <div class="blog-card-cover" style="${coverStyle}" aria-hidden="true">${coverInner}</div>
        <div class="blog-card-body">
          <div class="blog-card-date">${shortDate(p.date)}</div>
          <div class="blog-card-title">${esc(p.title_en)}</div>
          ${tagsHtml}
        </div>
      </a>`;
  }).join('\n      ');
  const enIndexJsonLd = JSON.stringify({
    "@context": "https://schema.org",
    "@graph": [
      {
        "@type": "BreadcrumbList",
        "itemListElement": [
          { "@type": "ListItem", "position": 1, "name": "Trace Logo's", "item": `${BASE_URL}/` },
          { "@type": "ListItem", "position": 2, "name": "Blog", "item": `${BASE_URL}/en/blog/` },
        ],
      },
      {
        "@type": "Blog",
        "name": "Trace Logo's Blog",
        "url": `${BASE_URL}/en/blog/`,
        "inLanguage": "en",
        "blogPost": posts.map(p => ({
          "@type": "BlogPosting",
          "headline": p.title_en,
          "url": `${BASE_URL}/en/blog/${p.slug}/`,
          "datePublished": p.date,
        })),
      },
    ],
  }, null, 2);
  const enIndexHtml = transformToEn(
    T_INDEX.replace(/\{\{(\w+)\}\}/g, (_, k) => {
      if (k === 'REL' || k === 'HOME_REL' || k === 'DATA_BASE') return '/';
      if (k === 'JSON_LD') return enIndexJsonLd;
      if (k === 'POST_CARDS') return enCards;
      return '';
    }),
    'blog/index.html',
    EN
  );
  fs.mkdirSync(path.join(ROOT, 'en', 'blog'), { recursive: true });
  fs.writeFileSync(path.join(ROOT, 'en', 'blog', 'index.html'), enIndexHtml, 'utf8');

  console.log(`✓ Blog: ${posts.length} posts + index (RU + EN)`);
}

main();
