#!/usr/bin/env node
/**
 * Regenerates js/version.js with a fresh ASSET_VERSION.
 *
 * SVG_URL_V (js/utils.js) is built from ASSET_VERSION and appended as ?v=
 * to every logo/emoji SVG, PNG and WebP preview URL. It must be a value
 * that only changes when asset content actually changes — NOT one computed
 * per page load (that defeats the 30-day browser cache set in vercel.json).
 *
 * Run this LAST, right before committing/deploying, whenever you've:
 *   - replaced/edited an existing SVG or PNG in assets/logos or assets/emoji
 *     (new files with new names don't need it — cache-busting only matters
 *     when a URL's content changes under the same filename)
 *   - changed anything under /js or /css
 *
 * Usage: node scripts/build-version.js [--dry-run]
 */

const fs = require('fs');
const path = require('path');

const DRY_RUN = process.argv.includes('--dry-run');
const OUT = path.join(__dirname, '..', 'js', 'version.js');

const version = new Date().toISOString().slice(0, 10).replace(/-/g, '');
const contents =
  `// Generated by scripts/build-version.js — run it after any change to\n` +
  `// assets/logos/*, assets/emoji/*, /js/* or /css/* so browsers bust their cache.\n` +
  `export const ASSET_VERSION = '${version}';\n`;

if (DRY_RUN) {
  console.log(`[dry-run] js/version.js -> ASSET_VERSION = '${version}'`);
} else {
  fs.writeFileSync(OUT, contents);
  console.log(`js/version.js -> ASSET_VERSION = '${version}'`);
}
