#!/usr/bin/env node
/**
 * Pushes cdn-dist/ (generated by build-cdn.js) to the trace-logos-cdn repo,
 * which serves it via GitHub Pages at cdn.trace-logos.ru.
 *
 * cdn-dist/ is a plain folder, not a git repo itself between runs — this
 * script re-inits it each time and force-pushes, since the deployed tree
 * should always exactly mirror the current manifest (no history to preserve).
 *
 * Usage:
 *   node scripts/deploy-cdn.js
 */

const path = require('path');
const { execFileSync } = require('child_process');
const fs = require('fs');

const ROOT    = path.resolve(__dirname, '..');
const OUT_DIR = path.join(ROOT, 'cdn-dist');
const REMOTE  = 'https://github.com/sixxset5-star/trace-logos-cdn.git';

function run(cmd, args) {
  execFileSync(cmd, args, { cwd: OUT_DIR, stdio: 'inherit' });
}

function main() {
  if (!fs.existsSync(OUT_DIR)) {
    console.error('cdn-dist/ не найдена — сначала запусти node scripts/build-cdn.js (или npm run build).');
    process.exit(1);
  }

  fs.rmSync(path.join(OUT_DIR, '.git'), { recursive: true, force: true });
  run('git', ['init', '-q']);
  run('git', ['checkout', '-q', '-b', 'main']);
  run('git', ['add', '-A']);

  try {
    run('git', ['commit', '-q', '-m', `CDN mirror sync (${new Date().toISOString().slice(0, 10)})`]);
  } catch {
    console.log('Нет изменений — cdn-dist уже соответствует последнему коммиту.');
    return;
  }

  run('git', ['remote', 'add', 'origin', REMOTE]);
  run('git', ['push', '-f', 'origin', 'main']);
  console.log('✓ Запушено в trace-logos-cdn (cdn.trace-logos.ru)');
}

main();
