const assert=require('node:assert/strict');
const {copy,equal}=require('../src/util');
let nextId=1;const defaults={name:'Layer',visible:true,opacity:1,blendMode:'NORMAL',x:0,y:0,width:200,height:120,rotation:0,fills:[],strokes:[],effects:[],layoutMode:'NONE',layoutPositioning:'AUTO',layoutAlign:'INHERIT',layoutGrow:0,constraints:{horizontal:'MIN',vertical:'MIN'},clipsContent:false,cornerRadius:0,boundVariables:{},explicitVariableModes:{},gridRowSpan:1,gridColumnSpan:1,gridChildHorizontalAlign:'AUTO',gridChildVerticalAlign:'AUTO'};
class Node {
 constructor(type,name,props={}){Object.assign(this,copy(defaults),props);this.type=type;this.name=name;this.id='n'+nextId++;this.parent=null;this.children=[];this.data={};this.removed=false;this.remote=false;this.key=this.id;this.main=null;this.description='';this.styles=[];this.characters='';this.hasMissingFont=false;this.componentProperties={};this.componentPropertyDefinitions={};this._gridRow=0;this._gridColumn=0;Object.defineProperties(this,{gridRowAnchorIndex:{get(){return this.parent?.layoutMode==='GRID'&&this.parent.gridItemsPositioning==='ROW_AUTO_FLOW'?Math.floor(this.parent.children.indexOf(this)/this.parent.gridColumnCount):this._gridRow}},gridColumnAnchorIndex:{get(){return this.parent?.layoutMode==='GRID'&&this.parent.gridItemsPositioning==='ROW_AUTO_FLOW'?this.parent.children.indexOf(this)%this.parent.gridColumnCount:this._gridColumn}}});}
 get relativeTransform(){return [[1,0,this.x],[0,1,this.y]]}set relativeTransform(v){this.x=v[0][2];this.y=v[1][2]}
 get absoluteBoundingBox(){return {x:this.x,y:this.y,width:this.width,height:this.height}}
 getPluginData(k){return this.data[k]||''}setPluginData(k,v){this.data[k]=v}
 insertChild(i,n){if(this.type==='INSTANCE')throw Error('Cannot change instance structure');for(let p=this.parent;p;p=p.parent)if(p.type==='INSTANCE')throw Error('Cannot change nested structure');if(n.parent)n.parent.children.splice(n.parent.children.indexOf(n),1);n.parent=this;this.children.splice(i,0,n);if(this.layoutMode==='GRID'&&this.gridItemsPositioning!=='ROW_AUTO_FLOW'){let cell=0;while(this.children.some(c=>c!==n&&c.gridRowAnchorIndex===Math.floor(cell/this.gridColumnCount)&&c.gridColumnAnchorIndex===cell%this.gridColumnCount))cell++;n._gridRow=Math.floor(cell/this.gridColumnCount);n._gridColumn=cell%this.gridColumnCount;}}
 appendChild(n){this.insertChild(this.children.length,n)}
 remove(){if(this.removed)return;if(this.parent)this.parent.children.splice(this.parent.children.indexOf(this),1);this.parent=null;this.removed=true;this.children.slice().forEach(n=>n.remove())}
 clone(){const n=duplicate(this);figma.currentPage.appendChild(n);return n}
 detachInstance(){assert.equal(this.type,'INSTANCE');const parent=this.parent,index=parent.children.indexOf(this),n=duplicate(this);n.type='FRAME';n.main=null;this.remove();parent.insertChild(index,n);return n}
 createInstance(){assert.equal(this.type,'COMPONENT');const n=duplicate(this);n.type='INSTANCE';n.main=this;inheritIds(this,n,n.id);for(const [key,def]of Object.entries(this.componentPropertyDefinitions))n.componentProperties[key]={type:def.type,value:copy(def.defaultValue)};figma.currentPage.appendChild(n);return n}
 async getMainComponentAsync(){return this.main}
 async getInstancesAsync(){const out=[];function walk(n){if(n.type==='INSTANCE'&&n.main===this)out.push(n);n.children.forEach(c=>walk.call(this,c))}walk.call(this,figma.currentPage);return out}
 swapComponent(c){const old=this.children;const newKids=c.children.map(duplicate);newKids.forEach(n=>{const same=old.find(o=>o.name===n.name&&o.type===n.type);if(same){Object.keys(defaults).forEach(k=>n[k]=copy(same[k]));n.characters=same.characters;n.styles=copy(same.styles);}});old.forEach(n=>{n.parent=null});this.children=newKids;newKids.forEach(n=>n.parent=this);this.main=c;}
 setProperties(p){for(const k of Object.keys(p)){this.componentProperties[k]={type:this.componentProperties[k]?.type||'TEXT',value:p[k]};if(k.split('#')[0]==='Divider')this.children.filter(n=>n.isDivider).forEach(n=>n.visible=p[k]);}}
 editComponentProperty(key,value){Object.assign(this.componentPropertyDefinitions[key],value);return key}
 setGridChildPosition(row,column){assert.equal(this.parent.layoutMode,'GRID');if(this.parent.gridItemsPositioning==='ROW_AUTO_FLOW')throw Error('Auto-flow grid');if(this.parent.children.some(n=>n!==this&&n.gridRowAnchorIndex===row&&n.gridColumnAnchorIndex===column))throw Error('Grid cell occupied');this._gridRow=row;this._gridColumn=column;}
 resizeWithoutConstraints(w,h){this.width=w;this.height=h}
 async setFillsAsync(v){this.fills=copy(v)}async setStrokesAsync(v){this.strokes=copy(v)}async setFillStyleIdAsync(v){this.fillStyleId=v}async setStrokeStyleIdAsync(v){this.strokeStyleId=v}async setEffectStyleIdAsync(v){this.effectStyleId=v}async setTextStyleIdAsync(v){this.textStyleId=v}async setGridStyleIdAsync(v){this.gridStyleId=v}async setReactionsAsync(v){this.reactions=v}
 getRangeAllFontNames(){return this.getStyledTextSegments().map(s=>s.fontName)}
 getStyledTextSegments(){const out=[];let start=0;for(let i=0;i<this.characters.length;i++){const style=this.styles[i]||this.styles[0]||{fontName:{family:'Inter',style:'Regular'},fontSize:12};if(out.length&&equal(style,out[out.length-1]._style)){out[out.length-1].end=i+1;out[out.length-1].characters+=this.characters[i];}else out.push(Object.assign({start:i,end:i+1,characters:this.characters[i],_style:copy(style)},copy(style)));}return out.map(s=>{delete s._style;return s})}
}
for(const [field,method]of Object.entries({fontName:'FontName',fontSize:'FontSize',textCase:'TextCase',textDecoration:'TextDecoration',letterSpacing:'LetterSpacing',lineHeight:'LineHeight',fills:'Fills',textStyleId:'TextStyleIdAsync',hyperlink:'Hyperlink',listOptions:'ListOptions',indentation:'Indentation',openTypeFeatures:'OpenTypeFeatures'}))Node.prototype['setRange'+method]=function(start,end,value){for(let i=start;i<end;i++){this.styles[i]=Object.assign({},this.styles[i]||this.styles[0]||{fontName:{family:'Inter',style:'Regular'},fontSize:12});this.styles[i][field]=copy(value);}};
function inheritIds(source,target,rootId){source.children.forEach((child,i)=>{target.children[i].id='I'+rootId+';'+child.id.replace(/^I/,'');inheritIds(child,target.children[i],rootId)})}
function duplicate(source){const n=new Node(source.type,source.name);Object.keys(source).forEach(k=>{if(!['parent','children','id','main','removed'].includes(k))n[k]=copy(source[k])});n.main=source.main;n.children=source.children.map(duplicate);n.children.forEach(c=>c.parent=n);return n}
function reset(){const page=new Node('PAGE','Page');global.figma={currentPage:page,createFrame(){const n=new Node('FRAME','Frame');page.appendChild(n);return n},createComponentFromNode(n){assert.equal(n.type,'FRAME');n.type='COMPONENT';return n},async loadFontAsync(font){if(font.family==='Missing')throw Error('Missing font')},viewport:{scrollAndZoomIntoView(){}},variables:{async getVariableByIdAsync(id){return {id}}}};return page}
function frame(name,kids=[],props={}){const n=new Node('FRAME',name,props);kids.forEach(c=>n.appendChild(c));return n}
function text(value,name='Title',styles){const n=new Node('TEXT',name,{width:80,height:18});n.characters=value;n.styles=styles||[{fontName:{family:'Inter',style:'Regular'},fontSize:12}];return n}
function card(value='Отряды',extra=false){return frame('Card',[text(value),...(extra?[new Node('RECTANGLE','Badge',{width:20,height:20,x:100})]:[]),frame('Button',[],{width:80,height:28,y:70})])}
function mount(...nodes){nodes.forEach(n=>figma.currentPage.appendChild(n));return nodes}
function asComponent(n){n.type='COMPONENT';return n}
function instance(n){return n.createInstance()}
const {analyze}=require('../src/plan');const {commit}=require('../src/transaction');const {buildSchema}=require('../src/schema');const {capture}=require('../src/snapshot');
let passed=0;async function test(name,fn){reset();try{await fn();passed++;console.log('✓ '+name)}catch(e){console.error('✗ '+name);throw e}}
async function convert(nodes,base=0){const plan=await analyze(nodes,base);assert.deepEqual(plan.conflicts.filter(c=>c.severity==='error'),[]);return {plan,result:await commit(nodes,plan)}}
(async()=>{
 await test('01 FRAME + FRAME: текст и позиции',async()=>{const [a,b]=mount(card(),card('Тайные задания'));b.x=300;const {result}=await convert([a,b]);assert.equal(result.outputs[0].type,'COMPONENT');assert.equal(result.outputs[1].type,'INSTANCE');assert.equal(result.outputs[1].children[0].characters,'Тайные задания');assert.equal(result.outputs[1].x,300);assert(a.removed&&b.removed)});
 await test('02 Badge во второй карточке: hidden / visible',async()=>{const [a,b]=mount(card(),card('B',true));const {result}=await convert([a,b]);assert.equal(result.outputs[0].children[1].name,'Badge');assert.equal(result.outputs[0].children[1].visible,false);assert.equal(result.outputs[1].children[1].visible,true)});
 await test('03 Badge только в первой карточке',async()=>{const [a,b]=mount(card('A',true),card('B'));const {result}=await convert([a,b]);assert.equal(result.outputs[0].children[1].visible,true);assert.equal(result.outputs[1].children[1].visible,false)});
 await test('04 Повторяющийся Badge в трёх карточках — один role',async()=>{const nodes=mount(card(),card('B',true),card('C',true),card('D',true));const {result}=await convert(nodes);assert.equal(result.outputs[0].children.filter(n=>n.name==='Badge').length,1)});
 for(const [name,types]of [['05 FRAME + INSTANCE',['FRAME','INSTANCE']],['06 INSTANCE + FRAME',['INSTANCE','FRAME']],['07 INSTANCE + INSTANCE',['INSTANCE','INSTANCE']],['08 COMPONENT + FRAME',['COMPONENT','FRAME']],['09 COMPONENT + INSTANCE',['COMPONENT','INSTANCE']],['10 COMPONENT + COMPONENT',['COMPONENT','COMPONENT']]])await test(name,async()=>{const nodes=types.map((type,i)=>{const n=card('Text '+i);if(type==='FRAME')return n;const c=asComponent(n);figma.currentPage.appendChild(c);return type==='COMPONENT'?c:instance(c)});mount(...nodes);const {result}=await convert(nodes);assert.equal(result.outputs[0].type,'COMPONENT');assert.equal(result.outputs[1].children[0].characters,'Text 1');assert(nodes.every(n=>n.removed))});
 await test('11 Внешний инстанс старого компонента сохраняет связь',async()=>{const a=asComponent(card()),b=card('B');mount(a,b);const outside=instance(a);outside.children[0].characters='Override';const {result}=await convert([a,b]);assert.equal(outside.main,result.outputs[0]);assert.equal(outside.children[0].characters,'Override')});
 for(const [name,remote]of [['12 Nested local instance',false],['13 Nested remote instance',true]])await test(name,async()=>{const c=asComponent(frame('Inner',[text('Inner')]));c.remote=remote;mount(c);const a=frame('A',[instance(c)]),b=frame('B',[instance(c)]);b.children[0].children[0].characters='Other';mount(a,b);const {result}=await convert([a,b]);assert.equal(result.outputs[1].children[0].children[0].characters,'Other');assert.equal(c.children[0].characters,'Inner')});
 await test('14 Extra внутри nested Instance → локальный общий компонент',async()=>{const c=asComponent(frame('Inner',[text('Inner')])),d=asComponent(frame('Inner',[text('Inner'),new Node('RECTANGLE','Badge',{width:20,height:20})]));mount(c,d);const a=frame('A',[instance(c)]),b=frame('B',[instance(d)]);mount(a,b);const {result}=await convert([a,b]);assert.equal(result.helpers,1);assert.equal(result.outputs[0].children[0].children[1].visible,false);assert.equal(result.outputs[1].children[0].children[1].visible,true)});
 await test('15 Mixed fonts: диапазоны сохраняются',async()=>{const fonts=[{fontName:{family:'Inter',style:'Regular'},fontSize:12},{fontName:{family:'Roboto',style:'Bold'},fontSize:16}];const a=frame('A',[text('AB')]),b=frame('B',[text('XY','Title',fonts)]);mount(a,b);const {result}=await convert([a,b]);assert.deepEqual(result.outputs[1].children[0].getRangeAllFontNames(),fonts.map(s=>s.fontName))});
 for(const [name,type]of [['16 Одинаковые Frame names','FRAME'],['17 Несколько Text на одном уровне','TEXT'],['18 Несколько Vector','VECTOR']])await test(name,async()=>{const make=()=>frame('Card',[new Node(type,'Same'),new Node(type,'Same')]);const nodes=mount(make(),make());const plan=await analyze(nodes,0);assert(plan.summary.ambiguous>0);assert(nodes.every(n=>!n.removed))});
 await test('19 Mask сохраняется',async()=>{const make=()=>frame('Card',[new Node('RECTANGLE','Mask',{isMask:true})]);const nodes=mount(make(),make());const {result}=await convert(nodes);assert.equal(result.outputs[1].children[0].isMask,true)});
 await test('20 Boolean operation: различия блокируют применение',async()=>{const a=frame('A',[new Node('BOOLEAN_OPERATION','Boolean',{booleanOperation:'UNION'})]),b=frame('B',[new Node('BOOLEAN_OPERATION','Boolean',{booleanOperation:'SUBTRACT'})]);mount(a,b);const plan=await analyze([a,b],0);assert(plan.summary.errors>0)});
 await test('21 Absolute positioning и dimensions',async()=>{const a=card(),b=card('B');b.children[1].layoutPositioning='ABSOLUTE';b.children[1].x=41;b.children[1].width=96;mount(a,b);const {result}=await convert([a,b]);assert.equal(result.outputs[1].children[1].x,41);assert.equal(result.outputs[1].children[1].width,96)});
 await test('22 Auto Layout, padding/gap и sibling index',async()=>{const a=card(),b=card('B');a.layoutMode=b.layoutMode='VERTICAL';a.itemSpacing=8;b.itemSpacing=12;const parent=frame('Parent',[a,b],{layoutMode:'HORIZONTAL'});mount(parent);const {result}=await convert([a,b]);assert.deepEqual(parent.children,result.outputs);assert.equal(result.outputs[1].itemSpacing,12)});
 await test('23 Ошибка до commit: исходники живы, временных узлов нет',async()=>{const a=card(),b=card('B');b.children[0].hasMissingFont=true;mount(a,b);const plan=await analyze([a,b],0);assert(plan.summary.errors>0);assert.deepEqual(figma.currentPage.children,[a,b])});
 await test('24 Ошибка посередине commit: rollback identity/position/order',async()=>{const [a,b]=mount(card(),card('B'));b.x=300;const plan=await analyze([a,b],0);await assert.rejects(commit([a,b],plan,()=>{},{afterPlacement(){throw Error('Injected failure')}}),/Исходные плашки восстановлены/);assert.deepEqual(figma.currentPage.children,[a,b]);assert(!a.removed&&!b.removed);assert.equal(b.x,300)});
 await test('25 Повторный запуск: стабильные role IDs',async()=>{const nodes=mount(card(),card('B',true));const {result}=await convert(nodes);const before=result.outputs[0].children.map(n=>n.getPluginData('plate-role-id'));const second=await convert(result.outputs);assert.deepEqual(second.result.outputs[0].children.map(n=>n.getPluginData('plate-role-id')),before)});
 await test('Смена макета после preview блокирует commit',async()=>{const [a,b]=mount(card(),card('B'));const plan=await analyze([a,b],0);b.children[0].characters='Changed';await assert.rejects(commit([a,b],plan),/Макет изменился/);assert.deepEqual(figma.currentPage.children,[a,b])});
 await test('Rollback внешнего swap сохраняет overrides',async()=>{const a=asComponent(card()),b=card('B');mount(a,b);const outside=instance(a);outside.children[0].characters='Override';const plan=await analyze([a,b],0);await assert.rejects(commit([a,b],plan,()=>{},{afterSwaps(){throw Error('Injected swap failure')}}),/Исходные плашки восстановлены/);assert.equal(outside.main,a);assert.equal(outside.children[0].characters,'Override');assert(!a.removed&&!b.removed)});
 await test('Rollback после частичного удаления восстанавливает выбранную связь',async()=>{const a=asComponent(card());mount(a);const b=instance(a);b.children[0].characters='Override';const plan=await analyze([a,b],0);const remove=Node.prototype.remove;let fail=true;Node.prototype.remove=function(){if(this===b&&fail){fail=false;throw Error('Injected removal failure')}return remove.call(this)};try{await assert.rejects(commit([a,b],plan),/Исходные плашки восстановлены/);}finally{Node.prototype.remove=remove;}assert.equal(figma.currentPage.children[0].type,'COMPONENT');assert.equal(b.main,figma.currentPage.children[0]);assert.equal(b.children[0].characters,'Override');assert.equal(figma.currentPage.children.length,2)});
 for(const [label,changed]of [['Неизменные read-only OpenType сохраняются',false],['Различия read-only OpenType блокируются',true]])await test(label,async()=>{const setter=Node.prototype.setRangeOpenTypeFeatures;Node.prototype.setRangeOpenTypeFeatures=undefined;Node.prototype.getRangeOpenTypeFeatures=function(){return this.styles[0]?.openTypeFeatures||{}};try{const a=card(),b=card('B');a.children[0].styles[0].openTypeFeatures={};b.children[0].styles[0].openTypeFeatures=changed?{liga:true}:{};mount(a,b);const plan=await analyze([a,b],0);assert.equal(plan.summary.errors>0,changed);}finally{Node.prototype.setRangeOpenTypeFeatures=setter;delete Node.prototype.getRangeOpenTypeFeatures;}});
 function speakers(){
   const row=asComponent(frame('Frame 62727',[text('Текст','Content'),new Node('RECTANGLE','Divider'),new Node('RECTANGLE','Divider')],{height:42}));row.id='1123:4265';row.children.forEach((n,i)=>{n.id='1123:'+String(4266+i);if(i)n.isDivider=true;});row.componentPropertyDefinitions={'Divider#1123:9':{type:'BOOLEAN',defaultValue:true}};mount(row);
   const rows=Array.from({length:6},(_,i)=>{const n=instance(row);n.id='1374:'+String(9723+i);n.name=i===1?'Frame 62731':'Frame 62730';inheritIds(row,n,n.id);return n});
   const list=frame('Frame 1948755753',rows,{layoutMode:'VERTICAL'});list.id='1374:9700';
   const photo=new Node('RECTANGLE','Rectangle 1771995285',{fills:[{type:'IMAGE',imageHash:'base',scaleMode:'CROP',imageTransform:[[1,0,0],[0,1,0]],filters:{contrast:.2}}]});photo.id='1374:9701';
   const main=asComponent(frame('speaker-card',[photo,list],{layoutMode:'VERTICAL',width:370,height:450}));main.id='1374:9906';main.componentPropertyDefinitions={'Label#1374:9':{type:'TEXT',defaultValue:'Default'}};mount(main);
   const cards=Array.from({length:7},(_,i)=>{const n=instance(main);n.x=i*400;n.height=450+(i===1||i===2||i===3?42:0);n.componentProperties['Label#1374:9'].value='Card '+i;n.children[0].fills[0].imageHash='photo '+i;n.children[0].fills[0].imageTransform=[[1.1,0,.01*i],[0,1.1,-.1]];const items=n.children[1].children;const count=i>=1&&i<=3?6:5;items.forEach((item,j)=>{item.name=j===1?'Frame 62731':'Frame 62730';item.children[0].characters='Card '+i+' / Item '+j;item.setProperties({'Divider#1123:9':j!==count-1});item.visible=j<count});return n});
   return {main,cards,row};
 }
 await test('Общий speaker-card: 7 карточек, 5/6 строк, повторяющиеся имена',async()=>{const {main,cards}=speakers();const before=JSON.stringify(main.componentPropertyDefinitions);const {plan,result}=await convert(cards);assert.equal(plan.summary.ambiguous,0);assert.equal(result.helpers,0);assert.equal(result.outputs[0].type,'COMPONENT');assert.equal(result.outputs.length,7);assert.equal(result.outputs[0].children[1].children.length,6);assert.equal(figma.skipInvisibleInstanceChildren,false);assert.equal(JSON.stringify(main.componentPropertyDefinitions),before);assert(!main.removed);result.outputs.forEach((n,i)=>{const count=i>=1&&i<=3?6:5;const rows=n.children[1].children;assert.equal(rows[5].visible,count===6);assert.equal(rows[count-1].componentProperties['Divider#1123:9'].value,false);if(count===6)assert.equal(rows[4].componentProperties['Divider#1123:9'].value,true);rows.forEach((row,j)=>assert.equal(row.children[0].characters,'Card '+i+' / Item '+j));assert.equal(n.children[0].fills[0].imageHash,'photo '+i);assert.deepEqual(n.children[0].fills[0].imageTransform,[[1.1,0,.01*i],[0,1.1,-.1]]);assert.equal(n.height,450+(count===6?42:0));});assert.equal(result.outputs[0].componentPropertyDefinitions['Label#1374:9'].defaultValue,'Card 0');assert.equal(result.outputs[1].componentProperties['Label#1374:9'].value,'Card 1')});
 await test('Общий компонент: переименование строки не меняет её идентичность',async()=>{const {cards}=speakers();cards[3].children[1].children[2].name='Совсем другое имя';const plan=await analyze(cards,0);assert.equal(plan.summary.errors,0);const role=plan.schema.flat.find(r=>r.sample.origin?.path==='1374:9725');assert(role);assert.equal(role.members[3].name,'Совсем другое имя')});
 await test('Общий компонент: ошибка Commit сохраняет оригиналы и source main',async()=>{const {main,cards}=speakers();const original=figma.currentPage.children.slice();const plan=await analyze(cards,0);assert.deepEqual(figma.currentPage.children,original);await assert.rejects(commit(cards,plan,()=>{},{afterPlacement(){throw Error('Injected shared failure')}}),/Исходные плашки восстановлены/);assert.deepEqual(figma.currentPage.children,original);assert(cards.every(n=>!n.removed&&n.main===main))});
 await test('Изменение исходного main после Preview блокирует Commit',async()=>{const {main,cards}=speakers();const plan=await analyze(cards,0);main.children[0].fills[0].imageHash='Changed master';await assert.rejects(commit(cards,plan),/Исходный компонент изменился/);assert(cards.every(n=>!n.removed))});
 await test('Общий компонент: другая основа, readonly grid и rollback',async()=>{for(const mode of ['MANUAL','ROW_AUTO_FLOW']){reset();const {cards}=speakers();const grid=frame('Grid',[],{layoutMode:'GRID',gridItemsPositioning:mode,gridColumnCount:3});mount(grid);cards.forEach(n=>grid.appendChild(n));const plan=await analyze(cards,1);await assert.rejects(commit(cards,plan,()=>{},{afterPlacement(){throw Error('Injected grid failure')}}),/Исходные плашки восстановлены/);assert.deepEqual(grid.children,cards);cards.forEach((n,i)=>{assert.equal(n.gridRowAnchorIndex,Math.floor(i/3));assert.equal(n.gridColumnAnchorIndex,i%3)});const {result}=await convert(cards,1);assert.equal(result.outputs[1].type,'COMPONENT');assert.equal(result.outputs[1].children[1].children[5].visible,true);result.outputs.forEach((n,i)=>{assert.equal(n.gridRowAnchorIndex,Math.floor(i/3));assert.equal(n.gridColumnAnchorIndex,i%3)})}});

 await test('Выбор другой основы',async()=>{const [a,b]=mount(card(),card('B',true));const {result}=await convert([a,b],1);assert.equal(result.outputs[1].type,'COMPONENT');assert.equal(result.outputs[1].children[1].visible,true)});
 console.log(passed+' сценариев: OK (модель Figma API, не живой редактор).');
})().catch(e=>{console.error(e.stack);process.exitCode=1});
